name: fuck me till the daylightğŸ¥µ#ä¿®æ”¹ä½ çš„åç§°

on:
  workflow_dispatch:
  schedule:
    - cron: "29 8 * * 5" # ä¿®æ”¹ä½ çš„å®šæ—¶é…ç½®
    
jobs:
  setup:
    env:
      EPÎ™C_EMAÎ™L: ${{ secrets.EPIC_EMAIL }}
      EPÎ™C_PASSWÎŸRD: ${{ secrets.EPIC_PASSWORD }}
      PUSHER_TELEGRAM: ${{ secrets.PUSHER_TELEGRAM }}
      PLAYER: ${{ secrets.EPIC_PLAYER }}
    runs-on: ubuntu-latest
    steps:
      - name: Scaffold Claim
        run: |
          docker run --rm --pull always \
          -e EPÎ™C_EMAÎ™L \
          -e EPÎ™C_PASSWÎŸRD \
          -e PUSHER_TELEGRAM \
          -e PLAYER \
          ech0sec/awesome-epic:daddy python3 main.py claim 
